# Generated by Django 5.0.3 on 2024-03-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_password_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_shelter',
        ),
    ]
