# Generated by Django 5.0.3 on 2024-03-07 21:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ('-published',)},
        ),
        migrations.AddField(
            model_name='pet',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
