# Generated by Django 5.0.3 on 2024-03-08 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_options_pet_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='shelter',
            new_name='user',
        ),
    ]
