# Generated by Django 5.0.3 on 2024-03-22 08:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_rename_shelter_pet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
